name = "WheedenChapter2"
defaultTargets = ["WheedenChapter2"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.28.0"

[[lean_lib]]
name = "WheedenChapter2"
globs = ["WheedenChapter2.+"]
