name = "RudinExercises"
defaultTargets = ["RudinChapter1", "RudinChapter2", "RudinChapter3", "RudinChapter4", "RudinChapter5", "RudinChapter6", "WheedenChapter1", "WheedenChapter2", "IntroSmoothManifoldsChapter1", "IntroSmoothManifoldsChapter2", "IntroSmoothManifoldsChapter3", "IntroSmoothManifoldsChapter4", "IntroSmoothManifoldsChapter5", "IntroSmoothManifoldsChapter6", "IntroSmoothManifoldsChapter7", "IntroSmoothManifoldsChapter8", "IntroSmoothManifoldsChapter9", "IntroSmoothManifoldsChapter10", "IntroSmoothManifoldsChapter11", "IntroSmoothManifoldsChapter12", "IntroSmoothManifoldsChapter13", "IntroSmoothManifoldsChapter14"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.28.0"

[[lean_lib]]
name = "RudinChapter1"
globs = ["RudinChapter1.+"]

[[lean_lib]]
name = "RudinChapter2"
globs = ["RudinChapter2.+"]

[[lean_lib]]
name = "RudinChapter3"
globs = ["RudinChapter3.+"]

[[lean_lib]]
name = "RudinChapter4"
globs = ["RudinChapter4.+"]

[[lean_lib]]
name = "RudinChapter5"
globs = ["RudinChapter5.+"]

[[lean_lib]]
name = "RudinChapter6"
globs = ["RudinChapter6.+"]

[[lean_lib]]
name = "WheedenChapter1"
globs = ["WheedenChapter1.+"]

[[lean_lib]]
name = "WheedenChapter2"
globs = ["WheedenChapter2.+"]

[[lean_lib]]
name = "IntroSmoothManifoldsChapter1"
globs = ["IntroSmoothManifoldsChapter1.+"]

[[lean_lib]]
name = "IntroSmoothManifoldsChapter2"
globs = ["IntroSmoothManifoldsChapter2.+"]

[[lean_lib]]
name = "IntroSmoothManifoldsChapter3"
globs = ["IntroSmoothManifoldsChapter3.+"]

[[lean_lib]]
name = "IntroSmoothManifoldsChapter4"
globs = ["IntroSmoothManifoldsChapter4.+"]

[[lean_lib]]
name = "IntroSmoothManifoldsChapter5"
globs = ["IntroSmoothManifoldsChapter5.+"]

[[lean_lib]]
name = "IntroSmoothManifoldsChapter6"
globs = ["IntroSmoothManifoldsChapter6.+"]

[[lean_lib]]
name = "IntroSmoothManifoldsChapter7"
globs = ["IntroSmoothManifoldsChapter7.+"]

[[lean_lib]]
name = "IntroSmoothManifoldsChapter8"
globs = ["IntroSmoothManifoldsChapter8.+"]

[[lean_lib]]
name = "IntroSmoothManifoldsChapter9"
globs = ["IntroSmoothManifoldsChapter9.+"]

[[lean_lib]]
name = "IntroSmoothManifoldsChapter10"
globs = ["IntroSmoothManifoldsChapter10.+"]

[[lean_lib]]
name = "IntroSmoothManifoldsChapter11"
globs = ["IntroSmoothManifoldsChapter11.+"]

[[lean_lib]]
name = "IntroSmoothManifoldsChapter12"
globs = ["IntroSmoothManifoldsChapter12.+"]

[[lean_lib]]
name = "IntroSmoothManifoldsChapter13"
globs = ["IntroSmoothManifoldsChapter13.+"]

[[lean_lib]]
name = "IntroSmoothManifoldsChapter14"
globs = ["IntroSmoothManifoldsChapter14.+"]
